import Khachiyan.GeometricBound

/-!
# T05: sequences of exact central cuts

This module implements T05 of `proof.md`. Every cut uses the canonical center
of the current body's exact maximum-volume inscribed ellipsoid. Convex-body
properties and positive finite volume are derived throughout the sequence.
-/

noncomputable section
open scoped ENNReal MatrixOrder Matrix.Norms.L2Operator RealInnerProductSpace
open Matrix Set MeasureTheory

namespace Khachiyan

variable {n : ℕ} [NeZero n]

theorem centralCutSequence_isConvexBody {K : ℕ → Set (V n)} (hK0 : IsConvexBody (K 0))
    {p : ℕ → V n} (hp : ∀ k, p k ≠ 0)
    (hstep : ∀ k, K (k + 1) = K k ∩ centralHalfspace (johnCenter (K k)) (p k)) :
    ∀ k, IsConvexBody (K k) := by
  intro k
  induction k with
  | zero => exact hK0
  | succ k ih =>
    rw [hstep k]
    exact john_center_cut_isConvexBody ih (hp k)

/-- The multiplicative bound for actual extended-real Lebesgue volumes. -/
theorem centralCutSequence_volume_le {K : ℕ → Set (V n)} (hK0 : IsConvexBody (K 0))
    {p : ℕ → V n} (hp : ∀ k, p k ≠ 0)
    (hstep : ∀ k, K (k + 1) = K k ∩ centralHalfspace (johnCenter (K k)) (p k))
    (N : ℕ) : maxEllipsoidVolume (K N) ≤
      ENNReal.ofReal (rStar ^ N) * maxEllipsoidVolume (K 0) := by
  have hb := centralCutSequence_isConvexBody hK0 hp hstep
  induction N with
  | zero => simp
  | succ N ih =>
    calc
      maxEllipsoidVolume (K (N + 1)) =
          maxEllipsoidVolume (K N ∩ centralHalfspace (johnCenter (K N)) (p N)) := by rw [hstep]
      _ ≤ ENNReal.ofReal rStar * maxEllipsoidVolume (K N) :=
        john_center_cut_volume_le (hb N) (hp N)
      _ ≤ ENNReal.ofReal rStar *
          (ENNReal.ofReal (rStar ^ N) * maxEllipsoidVolume (K 0)) := by gcongr
      _ = ENNReal.ofReal (rStar ^ (N + 1)) * maxEllipsoidVolume (K 0) := by
        rw [pow_succ', ENNReal.ofReal_mul rStar_pos.le, mul_assoc]

theorem centralCutSequence_volume_bounds {K : ℕ → Set (V n)} (hK0 : IsConvexBody (K 0))
    {p : ℕ → V n} (hp : ∀ k, p k ≠ 0)
    (hstep : ∀ k, K (k + 1) = K k ∩ centralHalfspace (johnCenter (K k)) (p k))
    (N : ℕ) : 0 < maxEllipsoidVolume (K N) ∧ maxEllipsoidVolume (K N) < ∞ := by
  have hb := centralCutSequence_isConvexBody hK0 hp hstep N
  exact ⟨hb.maxEllipsoidVolume_pos, hb.maxEllipsoidVolume_lt_top⟩

theorem centralCutSequence_volume_le_real {K : ℕ → Set (V n)} (hK0 : IsConvexBody (K 0))
    {p : ℕ → V n} (hp : ∀ k, p k ≠ 0)
    (hstep : ∀ k, K (k + 1) = K k ∩ centralHalfspace (johnCenter (K k)) (p k))
    (N : ℕ) : (maxEllipsoidVolume (K N)).toReal ≤
      rStar ^ N * (maxEllipsoidVolume (K 0)).toReal := by
  have hleft := (centralCutSequence_volume_bounds hK0 hp hstep N).2
  have hright : ENNReal.ofReal (rStar ^ N) * maxEllipsoidVolume (K 0) < ∞ :=
    ENNReal.mul_lt_top ENNReal.ofReal_lt_top hK0.maxEllipsoidVolume_lt_top
  have h := (ENNReal.toReal_le_toReal hleft.ne hright.ne).mpr
    (centralCutSequence_volume_le hK0 hp hstep N)
  simpa only [ENNReal.toReal_mul, ENNReal.toReal_ofReal (pow_nonneg rStar_pos.le N)] using h

/-- The additive logarithmic progress bound, with positive finite denominators proved first. -/
theorem centralCutSequence_log_ratio_ge {K : ℕ → Set (V n)} (hK0 : IsConvexBody (K 0))
    {p : ℕ → V n} (hp : ∀ k, p k ≠ 0)
    (hstep : ∀ k, K (k + 1) = K k ∩ centralHalfspace (johnCenter (K k)) (p k))
    (N : ℕ) : (N : ℝ) * (Real.log 2 - (1 / 2 : ℝ)) ≤
      Real.log ((maxEllipsoidVolume (K 0)).toReal / (maxEllipsoidVolume (K N)).toReal) := by
  have h0 := ENNReal.toReal_pos_iff.mpr (centralCutSequence_volume_bounds hK0 hp hstep 0)
  have hN := ENNReal.toReal_pos_iff.mpr (centralCutSequence_volume_bounds hK0 hp hstep N)
  have h := Real.log_le_log hN (centralCutSequence_volume_le_real hK0 hp hstep N)
  rw [Real.log_mul (pow_pos rStar_pos N).ne' h0.ne', Real.log_pow] at h
  have hr : Real.log rStar = (1 / 2 : ℝ) - Real.log 2 := by
    rw [← Scalar.exp_logConstant, Real.log_exp]
    rfl
  rw [hr] at h
  rw [Real.log_div h0.ne' hN.ne']
  nlinarith

/-- T05 for any sequence satisfying the exact central-cut recurrence, including `N = 0`. -/
theorem t05 {K : ℕ → Set (V n)} (hK0 : IsConvexBody (K 0))
    {p : ℕ → V n} (hp : ∀ k, p k ≠ 0)
    (hstep : ∀ k, K (k + 1) = K k ∩ centralHalfspace (johnCenter (K k)) (p k))
    (N : ℕ) : IsConvexBody (K N) ∧
      maxEllipsoidVolume (K N) ≤ ENNReal.ofReal (rStar ^ N) * maxEllipsoidVolume (K 0) ∧
      (N : ℝ) * (Real.log 2 - (1 / 2 : ℝ)) ≤
        Real.log ((maxEllipsoidVolume (K 0)).toReal / (maxEllipsoidVolume (K N)).toReal) :=
  ⟨centralCutSequence_isConvexBody hK0 hp hstep N,
    centralCutSequence_volume_le hK0 hp hstep N,
    centralCutSequence_log_ratio_ge hK0 hp hstep N⟩

/-- The sequence generated by exact central cuts with the prescribed nonzero normals. -/
def centralCuts (K0 : Set (V n)) (p : ℕ → V n) : ℕ → Set (V n)
  | 0 => K0
  | k + 1 => centralCuts K0 p k ∩ centralHalfspace (johnCenter (centralCuts K0 p k)) (p k)

/-- T05 for the explicit recursive sequence, requiring only the initial body and nonzero normals. -/
theorem t05_centralCuts {K0 : Set (V n)} (hK0 : IsConvexBody K0)
    {p : ℕ → V n} (hp : ∀ k, p k ≠ 0) (N : ℕ) :
    IsConvexBody (centralCuts K0 p N) ∧
      maxEllipsoidVolume (centralCuts K0 p N) ≤ ENNReal.ofReal (rStar ^ N) * maxEllipsoidVolume K0 ∧
      (N : ℝ) * (Real.log 2 - (1 / 2 : ℝ)) ≤
        Real.log ((maxEllipsoidVolume K0).toReal / (maxEllipsoidVolume (centralCuts K0 p N)).toReal) :=
  t05 (K := centralCuts K0 p) hK0 hp (fun _ => rfl) N

end Khachiyan
